name: frontend

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions: { contents: read }

jobs:
  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ascend-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ascend-frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint (if script exists)
        run: |
          if [ -f package.json ] && node -e "process.exit(!(require('./package.json').scripts||{}).lint)"; then
          npm run lint
          else
          echo "No lint script in package.json; skipping lint."
          fi

      - name: Build
        env:
          VITE_API_URL: "http://localhost:8000"
        run: npm run build
